version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails_app
    environment:
      DATABASE_URL: postgres://username:password@db:5432/database_production?sslmode=disable
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/myapp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - /path/to/local/data:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  postgres_data:
