services:
  - type: web
    name: rails-app
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: rails-redis
          property: redisConnectionString
    plan: free

  - type: redis
    name: rails-redis
    plan: free

databases:
  - name: rails-db
    engine: postgres
    version: 13
    initialScript:
      filename: ./db/init.sql
