default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>

development:
  <<: *default
  database: database_development
  username: <%= ENV.fetch("DATABASE_USERNAME", "username") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

test:
  <<: *default
  database: database_test
  username: <%= ENV.fetch("DATABASE_USERNAME", "username") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

production:
  <<: *default
  database: database_production
  username: <%= ENV.fetch("DATABASE_USERNAME", "username") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
