default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: database_development
  username: <%= ENV.fetch("DATABASE_USERNAME", "username") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  port: <%= ENV.fetch("PORT", 5432) %> 
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>

test:
  <<: *default
  database: database_test
  username: <%= ENV.fetch("DATABASE_USERNAME", "username") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  port: <%= ENV.fetch("PORT", 5432) %>

production:
  <<: *default
  database: youtube_video_db
  username: <%= ENV.fetch("DATABASE_USERNAME", "username") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  port: <%= ENV.fetch("PORT", 5432) %>

